# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Atelier Socle SAS

blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/atelier-socle/swift-gherkin-generator/discussions
    about: Ask questions and get help from the community
